### ISSUE TITLE
Customize Tables: Use longer table names

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/spoonbill-web#100]
Excel allows up to 31 characters. We only need to abbreviate table names that would be longer than that.

In the Spoonbill library, we can discuss how to abbreviate long names.

![Screen Shot 2021-04-15 at 11 05 19 AM](https://user-images.githubusercontent.com/26463/114892141-7f5a7c80-9dda-11eb-9930-8a5b3b18e81c.png)

**Comment by sabahfromlondon** [comment]
Also I think the Table names should be more user friendly so will only say: "Parties", "Parties - Tenderers", "Planning", "Tenders"... right?

**Comment by sorenabell** [comment]
Discussion about Table s name abbreviation will continue in https://github.com/open-contracting/spoonbill/issues/45
