### ISSUE TITLE
Customize Tables: Sub-tables should only contain fields from the objects in the sub-array

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/spoonbill-web#101]
Here, the tables are identical. (Note: This particular screenshot also has the issue in #99.)

![Screen Shot 2021-04-15 at 11 08 22 AM](https://user-images.githubusercontent.com/26463/114892573-e5df9a80-9dda-11eb-8306-36ef6ab5d272.png)

**Comment by jpmckinney** [comment]
Also, after a split, the sub-array's columns should not be in the parent table.

**Comment by sorenabell** [comment]
Fixed [here](https://github.com/open-contracting/spoonbill/pull/28)
