### ISSUE TITLE
Customize Tables: Consider a second level of steps

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/spoonbill-web#103]
In the Customize Tables step, there is a second level of steps (one step per table). Issues:

* It's not clear to the user where they are in the process, since this second level of steps is invisible
* It's not possible to move back to edit the customization of an earlier table
* Using back button goes back to step 2 instead of previous table

https://user-images.githubusercontent.com/26463/114893607-de6cc100-9ddb-11eb-91d3-a62f4ee7d319.mov

**Comment by jpmckinney** [comment]
> It's not possible to move back to edit the customization of an earlier table

Actually, I just noticed the "Go back" button, which appears for later tables.

**Comment by sorenabell** [comment]
@sabahfromlondon @jpmckinney Please see the offered second-level navigation view (it is available in [Figma](https://www.figma.com/file/iYotf4uGSZwaRqKvqZ1wEZ/JSON-to-CSV-converter---OCP?node-id=576%3A235)). It seems to be smooth enough. What do you think?

![08_customize_tables_-_parties](https://user-images.githubusercontent.com/5451803/115903868-c694dd00-a46c-11eb-8d4f-68b40069676e.png)

**Comment by sabahfromlondon** [comment]
Thanks @sorenabell. Oleksandra and I are trying work this out today :)
