### ISSUE TITLE
Customize Tables: Display of Remove table button

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/spoonbill-web#104]
The Remove table button has the same appearance as the Save and Continue button (the most likely and least destructive action). 

The Remove table button does make a modal appear, so the user is unlikely to accidentally remove a table. That said, we might still consider using a different icon (e.g. trash) and/or color for the Remove table button.

I am also not sure if this sequence / position of the two buttons is the most appropriate @sabahfromlondon

![Screen Shot 2021-04-15 at 11 16 18 AM](https://user-images.githubusercontent.com/26463/114893810-11af5000-9ddc-11eb-97fd-02063c17247b.png)

**Comment by jpmckinney** [comment]
We discussed that it's okay to leave the button as-is. Clicking "Remove table" opens a modal with a "Remove table and continue" button. Since the button does advance the user to the next screen, its display is fine.

> I am also not sure if this sequence / position of the two buttons is the most appropriate

We didn't discuss this. It's not a major issue, but curious for @sabahfromlondon's thoughts.

**Comment by sabahfromlondon** [comment]
There is some precedence to invert the design of one of the buttons e.g. the remove button can be black with yellow writing and the icon inverted as well. 

Ideally they say in UX that there should only be one button, but we can't do that here, so it's ok to have them side by side.

**Comment by sorenabell** [comment]
Since we've already added a second level of navigation, I think we can focus in this issue on adding the "Restore table" button to the steps with single tables.
