### ISSUE TITLE
Edit Headings: Apply change button not visible if scrolled too far

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/spoonbill-web#105]
The button can either be moved to the bottom right (in which case it will be visible if the radio buttons are visible) or it can go below the radio buttons (though this increases the height of the page, which we might not want).

![Screen Shot 2021-04-15 at 11 23 31 AM](https://user-images.githubusercontent.com/26463/114895099-33f59d80-9ddd-11eb-88ff-e4b8bc42960b.png)

**Comment by sabahfromlondon** [comment]
I think we agreed that the button can be moved to just below the radio buttons and on the left hand side :)
