### ISSUE TITLE
Not all content translating into Spanish

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/spoonbill-web#142]
When I switch from English to Spanish not all of the content is translated.

See x2 screenshots attached. It can be seen that:
- The body text is not translated 
- The content in the FAQs on the right hand side is not t
ranslated the the text that is hyperlinked is. 

I have not checked the remainder of the screens.

<img width="773" alt="Spanish translation issue" src="https://user-images.githubusercontent.com/11212467/116533839-bef48e80-a8d9-11eb-931d-76039b413b24.png">

<img width="762" alt="Spanish translation issue 2" src="https://user-images.githubusercontent.com/11212467/116533876-c7e56000-a8d9-11eb-8847-07a8e4dfa860.png">

**Comment by sabahfromlondon** [comment]
Also noticed the Spanish user friendly headings and Spanish R headings are not always being applied. 

![screencapture-ocp12-open-contracting-org-2021-04-29-11_49_26](https://user-images.githubusercontent.com/11212467/116539679-10544c00-a8e1-11eb-9025-196727a0e976.png)

**Comment by sorenabell** [comment]
About the content of the page - it should be translated via [Transifex](https://www.transifex.com/open-contracting-partnership-1/spoonbill/dashboard/). I added a couple of translations to just check the work of the tool, but all of the rest requires a Spanish translator's work. 

As for the headings, we will check.

**Comment by jpmckinney** [comment]
Yes, I think the process can be:

* OCP reviews the English text and makes edits as desired
* OCP coordinates the Spanish translation, to be done in Transifex
* Quinta pulls in the Spanish translations from Transifex

**Comment by sorenabell** [comment]
You can use this [Chrome extension](https://chrome.google.com/webstore/detail/hypothesis-web-pdf-annota/bjfhmglciegochdpefhhlphglcehbmek?hl=en) to annotate text on the website. Just add your comments to the corresponding [group](https://hypothes.is/groups/5QQN8M14/spoonbill) (join it previously).
![image](https://user-images.githubusercontent.com/5451803/116572258-802ffa00-a914-11eb-85ce-b2b622b23054.png)

**Comment by sorenabell** [comment]
We have planned to add a mechanism that pulls the changes from Transifex automatically and periodically. 
@jpmckinney maybe every night?

**Comment by jpmckinney** [comment]
I'm not familiar with that workflow. Usually, if we add/change the English text, then we manually push to Transifex, ask the translators to make updates, and then manually pull from Transifex, before deploying the new version, so that the live version is always 100% translated.

We don't expect strings to change in Transifex between such processes.

**Comment by jpmckinney** [comment]
FYI @yolile

**Comment by yolile** [comment]
> Also noticed the Spanish user friendly headings and Spanish R headings are not always being applied.

And also, when selecting "English" some columns are in Spanish

![image](https://user-images.githubusercontent.com/6834122/118867773-7107f080-b8b1-11eb-9182-d8562bc20bab.png)

**Comment by jpmckinney** [comment]
@yolile or @sabahfromlondon: Can you check whether this is complete?

**Comment by sorenabell** [comment]
For some reason, those translated lines were pulled from Transifex but not applied on the UI. We ran the build once more and now most of the lines are translated on production. 
Just "There are * arrays in this table" needs the translation in Transifex now.

**Comment by sabahfromlondon** [comment]
@sorenabell I've found a few more places where the content is not translating into Spanish. See screenshots below:

Upload screen - see text in FAQ box:
<img width="722" alt="Screenshot 2021-08-24 085601" src="https://user-images.githubusercontent.com/11212467/130579211-ab01eace-1ed3-4342-a296-70c6084d6116.png">

Pop up box when clicking upload step
<img width="403" alt="Screenshot 2021-08-24 085623" src="https://user-images.githubusercontent.com/11212467/130579199-49c33942-a4a6-4460-ba79-4e99a8932291.png">

Text for arrays not translating:
<img width="725" alt="Screenshot 2021-08-24 090002" src="https://user-images.githubusercontent.com/11212467/130579875-a0ca9df4-d0f8-451c-b1ca-1cf897056671.png">
<img width="733" alt="Screenshot 2021-08-24 090053" src="https://user-images.githubusercontent.com/11212467/130579883-2e668e0f-861d-4e06-8529-d239a41c44c3.png">

When selecting to remove a table - I believe the Spanish for Cancel is Cancelar - I've see this happen to array tables and main tables
<img width="434" alt="Screenshot 2021-08-24 090134" src="https://user-images.githubusercontent.com/11212467/130580000-a96fc9eb-9501-4772-8529-81a7265f948a.png">

**Comment by yolile** [comment]
> When selecting to remove a table - I believe the Spanish for Cancel is Cancelar

@sabahfromlondon you are right :smile: 

@sorenabell I translated all the available strings in the Spanish resource in Transifex now. However, I don't see the strings from the pop-ups there.

**Comment by sorenabell** [comment]
We've fixed all UI translation issues for Spanish and Russian. 
https://www.awesomescreenshot.com/video/5361074?key=2862463c16caa0770e2359f446044432
Please check it on staging https://ocp12.open-contracting.org/

Please also check Transifex for any new untranslated lines from new UI flows or error messages.

**Comment by sabahfromlondon** [comment]
@sorenabell I've done a check and all the issues above look like they have been resolved. 

Did you have a link to the page when the user comes from the Data Registry? I will check that too.

Thanks

**Comment by sorenabell** [comment]
@sabahfromlondon  No, the previous workaround doesn't work now, we will have to wait for https://github.com/open-contracting/spoonbill-web/issues/347

**Comment by sabahfromlondon** [comment]
Ok well sounds like we can close this ticket then :)
