### ISSUE TITLE
Tables should have an order to make it easier for the user

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/spoonbill-web#143]
I noticed that the tables are not in any order in the select data screen. 

I think I should have been more explicit about this here as it is important for the tables to have an order in the customise tables step, to help the user learn the contracting process and associated data.

The feedback I had from people is that they really appreciated having a logical order to the tables to help them understand the data.

The order should be 
- Parties
- Planning
- Tenders
- Awards
- Contracts
- Documents
- Milestones
- Amendments

The video attached shows that there is no ordering in the select tables step or the customise table step.

https://user-images.githubusercontent.com/11212467/116535031-3119a300-a8db-11eb-95da-2ae4ebc84654.mp4

**Comment by sorenabell** [comment]
![image](https://user-images.githubusercontent.com/5451803/116689346-a7dc9c00-a9c0-11eb-9608-331cab60f784.png)

**Comment by sabahfromlondon** [comment]
Looks perfect, thanks!
