### ISSUE TITLE
Column ordering issue

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/spoonbill-web#145]
Is there any logic to the order to the columns in the data?

In the wireframes and the output spreadsheet the column order follows the data standard in the documentation and always starts with the OCID in order to make the data easier to work with.

Looking at the screens attached, I think it's important to maintain this order.

![screencapture-ocp12-open-contracting-org-2021-04-29-11_12_12](https://user-images.githubusercontent.com/11212467/116536469-dc772780-a8dc-11eb-94ec-72b8ae1781f2.png)

![screencapture-ocp12-open-contracting-org-2021-04-29-11_19_23](https://user-images.githubusercontent.com/11212467/116536472-dda85480-a8dc-11eb-8cf2-0abd906f21ea.png)

**Comment by jpmckinney** [comment]
We agreed on the call to follow the order in the schema (can be [downloaded here](https://standard.open-contracting.org/latest/en/schema/release/)). For additional fields, they can follow a natural order after their parent, e.g. `awards/period/extraField` goes after `awards/period/durationInDays`, not after `awards/items`.
