### ISSUE TITLE
Limit the height of a row in the tables

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/spoonbill-web#147]
It's helpful that the data in a cell is wrapped, but it have the effect of having a unreasonably tall row in a table. See screenshot attached. 

I don't think the user needs to be able to read the whole text in a cell (likely to be for fields such as tender description), so it would be good to limit the height of a row and just have "..." and cut off the text.

![screencapture-ocp12-open-contracting-org-2021-04-29-11_23_07](https://user-images.githubusercontent.com/11212467/116537944-ce2a0b00-a8de-11eb-8f65-7caf3bb8cc23.png)

**Comment by sorenabell** [comment]
Decided on: Maximum row height is 5 lines, the rest of the text will be concatenated.
