### ISSUE TITLE
OCDS Lite implementation

### ISSUE THREAD

**Issue by sorenabell** [open-contracting/spoonbill-web#154]
OCDS Lite Data template: https://docs.google.com/spreadsheets/d/1ov6IwG3c8CZTh7W9tZOw_VbVRen2oNNR1j1GnHSkufk/edit?usp=sharing

**Comment by sorenabell** [comment]
@sabahfromlondon The basic version of OCDS Lite (in accordance with the spoonbill library capabilities) is implemented. Please check it out on the [website](https://ocp12.open-contracting.org/).

**Comment by sabahfromlondon** [comment]
@sorenabell I've just tested this and each sheet has a couple of additional columns that are not required (rowID and parentID). See screenshot columns C and D:

<img width="521" alt="Screenshot 2021-05-25 152520" src="https://user-images.githubusercontent.com/11212467/119515246-9becbb80-bd6d-11eb-9bd2-e41b44a71362.png">

I'm assuming that the work to apply user friendly headings is WIP.

**Comment by sorenabell** [comment]
Maybe it is connected to this bug https://github.com/open-contracting/spoonbill/issues/90

**Comment by sabahfromlondon** [comment]
@jpmckinney the columns are on all sheets. Here's a sample flattened file:
[result_GhxKFzP.xlsx](https://github.com/open-contracting/spoonbill-web/files/6540511/result_GhxKFzP.xlsx)

**Comment by jpmckinney** [comment]
Thanks! Aren't those columns needed in awards_suppliers to easily link with awards?

Later, when we implement the OCDS Lite version that repeats data across sheets, we won't need them.

**Comment by sabahfromlondon** [comment]
Ok, but I thought we kept the Awards ID field to link awards_suppliers with awards: https://docs.google.com/spreadsheets/d/1L3CX3m4zh8o3YyKev9NT_pQc3h5eSQ9EmRxYmHXRVh8/edit?usp=sharing

**Comment by sorenabell** [comment]
@sabahfromlondon we've added updated for parentID and rowID for the OCDS Lite. Please check.

**Comment by sabahfromlondon** [comment]
@sorenabell I thought based on James's comment above we would keep the Row ID/Parent ID?

**Comment by sorenabell** [comment]
Based on the James' comment before that https://github.com/open-contracting/spoonbill-web/issues/154#issuecomment-848271504 rowID and parentID are necessary only for child tables (`awards_suppliers` in this case). Is that still correct?

**Comment by jpmckinney** [comment]
> Based on the James' comment before that [#154 (comment)](https://github.com/open-contracting/spoonbill-web/issues/154#issuecomment-848271504) rowID and parentID are necessary only for child tables (`awards_suppliers` in this case). Is that still correct?

The minimum is a rowID in `awards` and a parentID in `awards_suppliers` (whose values match a rowID in `awards`). These unique keys will allow the user to perform a lookup between the tables.

**Comment by sorenabell** [comment]
Yes, that was implemented. Please check.

**Comment by jpmckinney** [comment]
cc @yolile re: testing OCDS Lite.

**Comment by yolile** [comment]
@sorenabell I tested this and https://github.com/open-contracting/spoonbill/issues/105 and https://github.com/open-contracting/spoonbill/issues/67 persist. Also, the "ocid" column is missed in the "awards" and "awards_supplier" sheets. It seems that the ocid column was incorrectly removed in #265

**Comment by mariob0y** [comment]
> Also, the "ocid" column is missed in the "awards" and "awards_supplier" sheets. It seems that the ocid column was incorrectly removed in #265

@yolile `ocid` absence is fixed now - #271

**Comment by sabahfromlondon** [comment]
@sorenabell I just tested the OCDS Lite journey again and can see that user friendly headings have been automatically applied which is great. 

I also tested in Spanish and can see that the user friendly headings are still in English. Just checking that this is still in progress?

**Comment by sorenabell** [comment]
Yes, this is issue https://github.com/open-contracting/spoonbill-web/issues/142

**Comment by sabahfromlondon** [comment]
@sorenabell yes I can see the `ocid` in all sheets now

**Comment by jpmckinney** [comment]
Seems like this is done, so closing.
