### ISSUE TITLE
Make generate tables option unclickable when download is ready

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/spoonbill-web#156]
When the file(s) have been generated and is/are ready to download the user might not understand that this is another step and that they need to click the download button again.

I think we should 
- Change the generate button to a message that is not clickable
- Make the download button stand out more when the file is ready. Maybe use the yellow colour that we have used for the other buttons. 

<img width="608" alt="Download screen" src="https://user-images.githubusercontent.com/11212467/116571929-6df99000-a903-11eb-8718-0cd8aca086da.png">

**Comment by sorenabell** [comment]
@sabahfromlondon What action should trigger the file generation if we convert Generate button to a non-clickable message?
Maybe we can rename the Download button in the block below? See the attached screenshot.

![OCDS-Flatten-Tool1](https://user-images.githubusercontent.com/5451803/118236730-1cbed400-b49f-11eb-94a8-6218f8c53ff4.png)

**Comment by sabahfromlondon** [comment]
I don't understand this question: "What action should trigger the file generation if we convert Generate button to a non-clickable message?"

Do you mean the file download?

**Comment by sorenabell** [comment]
No. Immediately as the user is redirected to the Download page, the files are not ready for download yet. User has to trigger either CSV or XLSX file generation (currently via the "Generate tables as..." lines).

We don't generate them immediately because we don't know which format the user prefers and it will take unnecessary space in the storage to store both formats of files.

**Comment by sabahfromlondon** [comment]
I'm aware of that, but I still don't understand your question. Shall we have a quick call to discuss?

**Comment by sorenabell** [comment]
You mentioned two points, one of which:

- Change the generate button to a message that is not clickable

But if it is not clickable, then which action should generate files?

**Comment by sabahfromlondon** [comment]
Ok I think something like this will be easier for the user. 

Please try this for yourself: https://ma8bfh.axshare.com

Let me know if you have any questions.

**Comment by sorenabell** [comment]
Yes, looks great. Thank you.
We will follow your example (change title, remove "Generate..." links, rename buttons, etc.)

**Comment by sabahfromlondon** [comment]
Ok good. I wasn't sure if the spinner was taking to long. I recorded a video in case: https://drive.google.com/file/d/1cLyx5bzF6M30fRDwR32LsvyCke9Clw1O/view?usp=sharing
