### ISSUE TITLE
Increase height of available and selected table containers

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/spoonbill-web#159]
The max number of tables that will be available on this screen is 8, so we might as well increase the length of the container, so that scrolling will not be necessary

<img width="796" alt="available tables screen" src="https://user-images.githubusercontent.com/11212467/116578924-c9c71780-a909-11eb-9b41-b4eb6c659f2c.png">

**Comment by sorenabell** [comment]
Here is the updated view

![image](https://user-images.githubusercontent.com/5451803/116688983-28e76380-a9c0-11eb-9c57-d9510d77e01c.png)
