### ISSUE TITLE
"Split arrays into separate tables" is not working properly

### ISSUE THREAD

**Issue by yolile** [open-contracting/spoonbill-web#205]
Tested with https://www.contrataciones.gov.py/datos/api/v3/doc/ocds/releases/id/394282-adquisicion-cubiertas-maquinarias-vehiculos-utilitarios-annp-1-1621414358

In "Customize Tables" and "Tenders", when selecting "Split arrays into separate tables" the page stucks at: 
![image](https://user-images.githubusercontent.com/6834122/118861274-52522b80-b8aa-11eb-9ec4-2e61fd3cb22d.png)

To make it work you have to deactivate and then activate that option again, but, as mentioned in #204 the generated tables are empty

![image](https://user-images.githubusercontent.com/6834122/118861669-c391de80-b8aa-11eb-81f1-9effa982c6a0.png)

**Comment by sorenabell** [comment]
The issue was fixed. Please check.

**Comment by sabahfromlondon** [comment]
I tested this again with the attached file:
[sampledata.txt](https://github.com/open-contracting/spoonbill-web/files/6817290/sampledata.txt)

The Interface says there are three tables with arrays, which I selected - see screenshot:
<img width="683" alt="Screenshot 2021-07-14 164020" src="https://user-images.githubusercontent.com/11212467/125651233-3069988b-72b5-4b49-9323-134b1a2ecbf2.png">

The awards table doesn't provide me with an option to split the tables, even though it says there are **three** arrays:
<img width="879" alt="Screenshot 2021-07-14 164330" src="https://user-images.githubusercontent.com/11212467/125651452-d50ee4f6-faeb-4838-95a6-9b0c54a0e2cf.png">

The contracts table doesn't provide me with an option to split the tables, even though it says there are **four** arrays:
<img width="884" alt="Screenshot 2021-07-14 164443" src="https://user-images.githubusercontent.com/11212467/125651649-fcff2a49-bb8f-4d51-b6fa-67f3ef3754ff.png">

The tenders table doesn't provide me with an option to split the tables, even though it says there are **three** arrays:
<img width="872" alt="Screenshot 2021-07-14 164635" src="https://user-images.githubusercontent.com/11212467/125651879-3134f9f1-cf45-4ded-9475-4a41c84c2bbb.png">

**Comment by sorenabell** [comment]
But all of these tables contain less than 5 arrays. And we approved that only those tables that have 5 and more arrays are to be split.

**Comment by jpmckinney** [comment]
@sabahfromlondon I believe the behavior as implemented is to offer the option to split when there are 5 or more elements in the array.

Is the desired behavior to offer the option to split when there are 1-4 elements in the array (or 2-4?), and to always split (and disable the option) when there are 5 or more?

**Comment by sabahfromlondon** [comment]
@jpmckinney @sorenabell Yes you are both right. I did forget that bit.

I just tested again with another dataset that has tables with number of rows greater than 5 and contain at least one array.

This dataset from Honduras, the interface tells me contains 5 tables, two of which have an array (Awards and Contracts). Both tables have 9 rows, so there should be an option to split out those tables in the interface.

<img width="647" alt="Screenshot 2021-07-16 094840" src="https://user-images.githubusercontent.com/11212467/125920485-5a8d5b91-bd6a-4aa1-85a1-4bb2e85d065a.png">

However when I select those tables I can see that for neither Awards or Contracts am I given the option to split out the array -  see screen shots.
<img width="881" alt="Screenshot 2021-07-16 095031" src="https://user-images.githubusercontent.com/11212467/125920938-45ef1c82-a9df-46ed-b989-77244829b803.png">

<img width="868" alt="Screenshot 2021-07-16 095050" src="https://user-images.githubusercontent.com/11212467/125920940-571345c0-7e26-4e9e-88b0-df944e8bc521.png">

Am I doing something wrong? Here's the file I'm using to test: 
[honduras.txt](https://github.com/open-contracting/spoonbill-web/files/6829263/honduras.txt)

**Comment by sorenabell** [comment]
@sabahfromlondon Indeed, the main tables (Contracts and Awards) contain 9 rows each. But arrays, that may be potentially split into separate tables contain just 1 row each. This information is not displayed anywhere on UI that's why it may be confusing. Please check the code snippet below.

   ```
         "name": "contracts",
            "rows": 9,
            "arrays": {
                "/contracts/implementation/transactions": 1
            }
            "name": "awards",
            "rows": 9,
            "arrays": {
                "/awards/suppliers": 1
            }
```

**Comment by sabahfromlondon** [comment]
@sorenabell I see what you're saying and agree that the UI is confusing. This probably needs to be in a separate issue...

I tested with a much larger file size and there are a few things that aren't perfect, but @jpmckinney I'd be interested to get your thoughts as to whether these (and the UI issue above) need to hold back the launch? I'm happy to create separate issues if we can to come to these later.

1. Splitting out the arrays is a bit slow and my browser (Chrome) was coming up with a "Page Unresponsive" popup. If I select wait, then the tool does come good a short time later and successfully splits out the data. I tested this multiple times.

<img width="706" alt="Screenshot 2021-07-16 112307" src="https://user-images.githubusercontent.com/11212467/125934081-777de85a-aa3e-4dec-a972-13962e7d3557.png">

2. The split out arrays contain all of the rows in the dataset and not just the first five rows. Not terrible, especially as you have the ability to scroll for the table

3. If you remove a table and then restore it then not only do you get the whole table, but the scroll for the table is lost. Again not terrible, but say you have two split out tables and you remove and restore the first table. You may have to scroll a long way down to view the second table.

**Comment by sorenabell** [comment]
@sabahfromlondon I've created separate issues for all of the mentioned questions:

- #303
- #304
- #305
- #306

I've also added #306 issue for what we discussed during the last call.

@sabahfromlondon @jpmckinney please prioritize and approve these issues so that we could fix them.

**Comment by jpmckinney** [comment]
@sabahfromlondon How would you prioritize them? For context, here are all the priorities: https://docs.google.com/spreadsheets/d/1E6LjsjRXJz1GViLN4i11x-yJr1-bqs9XjyI9fMP99yg/edit#gid=0

**Comment by sabahfromlondon** [comment]
#303 and #306 may lead to users failing completely so are higher priority

#304 and #305 are lower priority as the user will still be able to use the tool. 

For the four issues, I would put the order of importance as 306, then 303, 305 and lastly 304

**Comment by jpmckinney** [comment]
Thanks! I've added "XL" and "M" priorities to the four issues in the spreadsheet.

**Comment by sorenabell** [comment]
Great, the prioritized list of tasks is updated.
We can start working on #303 and #305, but #306 and #304 require some final details.

**Comment by sorenabell** [comment]
Further discussion is in #306
