### ISSUE TITLE
"Upload_us" label not being replaced by its English description

### ISSUE THREAD

**Issue by yolile** [open-contracting/spoonbill-web#206]
https://ocp12.open-contracting.org/
![image](https://user-images.githubusercontent.com/6834122/118877364-5dae5280-b8bc-11eb-928a-ca66f85fceaf.png)

**Comment by sorenabell** [comment]
@yolile Could you describe the flow for this case?

**Comment by yolile** [comment]
The issue is on the main page of the tool, the label of the first step is not being replaced (I'm assuming that "Upload_us" is not the correct label for the first step). I updated the screen capture for a better image of where the issue is :)

**Comment by sorenabell** [comment]
I see. No, the translation was correctly pulled from [Transifex](https://www.transifex.com/open-contracting-partnership-1/spoonbill/translate/#en_US/web-app-ui/320521972?q=text%3Aupload). One of our developers probably added this to test the translation process. I will change it to the correct one.
