### ISSUE TITLE
Excel file: wrong party's role when having multiple roles

### ISSUE THREAD

**Issue by yolile** [open-contracting/spoonbill-web#207]
Tested with https://ocp12.open-contracting.org/#/download?url=f90d1d20-7903-431c-b53c-f5c78a54e9fc&selections=bf18a7e0-a1c9-4257-9a9e-e8263819ba21

The party row that is about the buyer and procuring entity has the role "buyerjoinableprocuringEntity"

**Comment by sorenabell** [comment]
@yolile Please note that the issue was closed via linked PR. But if the issue was fixed in the [library](https://github.com/open-contracting/spoonbill), it will require at least a web app re-build in order to see the resulting fixes on the [website](https://ocp12.open-contracting.org/).

**Comment by yolile** [comment]
@sorenabell I tested it with the command line and it is indeed solved, thank you!
