### ISSUE TITLE
Add FAQ box to explain what R friendly headings means

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/spoonbill-web#211]
What R friendly heads are might not be obvious to everyone, especially non-technical users. 

Please can we add a FAQ box in the area outlined where we can explain this?

Text to use:

FAQ

**What are R friendly headings?**
R is a coding language that is used for data visualization, statistical analysis and data science. Users that work with R prefer to have the column headings to be provided in a certain way so that the manual work to make the data ready for analysis is reduced.

![Inkedscreencapture-ocp12-open-contracting-org-2021-05-20-11_28_48_LI](https://user-images.githubusercontent.com/11212467/118964657-a3702700-b95f-11eb-81d3-12bd81b7e828.jpg)

**Comment by sorenabell** [comment]
![image](https://user-images.githubusercontent.com/5451803/119963923-515b8100-bfb1-11eb-8415-9a4e64c02d65.png)

**Comment by sabahfromlondon** [comment]
This one is missing a space between "science.Users" and "acertain"

**Comment by sorenabell** [comment]
Fixed.
