### ISSUE TITLE
List of missing column headings should be one item per line

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/spoonbill-web#214]
See screenshot attached. There is a heading that still has the /0/ when it should be omitted.

Each heading should also be on one line, so that it is easier for the user to read.

<img width="908" alt="Screenshot 2021-05-20 154304" src="https://user-images.githubusercontent.com/11212467/118999348-1ab6b280-b982-11eb-91ca-406573dba28a.png">

**Comment by sorenabell** [comment]
[Zeros in column headings #161](https://github.com/open-contracting/spoonbill-web/issues/161) is not closed yet.

As for the new lines, we will look into it.

**Comment by sorenabell** [comment]
![image](https://user-images.githubusercontent.com/5451803/119963956-5ae4e900-bfb1-11eb-9176-337ba7302f75.png)
