### ISSUE TITLE
Support for multiple files from the Data Registry

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/spoonbill-web#215]
Datasets in the registry can consist of multiple files. Web App Backend API should support multiple files submission initiated from the Data Registry.

Multiple provided files should be "merged" for export as if it is one document.

~Similarly, a user might have downloaded a bulk file from a publisher in ZIP, RAR or TAR.GZ format (these are the only formats in use by OCDS publishers), which might contain more than one JSON file. They might prefer to upload the bulk file instead of decompressing and unarchiving it.~

**Comment by sorenabell** [comment]
@jpmckinney We should add support for multiple files to the web app and library, should we add it to CLI too? Because we didn't include it in the initial estimation. Currently, I've created a separate issue for the future https://github.com/open-contracting/spoonbill/issues/141.

**Comment by jpmckinney** [comment]
I think it is okay to postpone the CLI support.

Regarding this issue, my original issue description was quite broad. For now, the minimum we need for registry integration is to support multiple individual files (in addition to #259). We don't need to support ZIP/RAR/TAR files that contain multiple files.

**Comment by mariob0y** [comment]
@jpmckinney Should these multiple files to be exported in one mutual document, or in separate documents?

**Comment by jpmckinney** [comment]
@mariob0y In one mutual document.

**Comment by myroslav** [comment]
Since web-centered feature appears to be less of a priority than the data registry integration one, I'd moved web-related piece to https://github.com/open-contracting/spoonbill-web/issues/274. Additionally the prerequisite, **multiple files support in the library** was moved to https://github.com/open-contracting/spoonbill/issues/145.

This feature will focus on Data Registry integration from now on.

**Comment by myroslav** [comment]
@jpmckinney should we focus only on multiple files with Local Paths (https://github.com/open-contracting/spoonbill-web/issues/260), or multiple files submitted as URLs should be supported within this issue as well.

One of the options for multiple URLs support is to have it implemented within Web UI issue (https://github.com/open-contracting/spoonbill-web/issues/274).

**Comment by jpmckinney** [comment]
Let's focus only on multiple files with local paths.

**Comment by sorenabell** [comment]
Instructions are here https://github.com/open-contracting/spoonbill-web/pull/299/files
