### ISSUE TITLE
Change heading and add admonition when file submitted from data registry

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/spoonbill-web#229]
e.g. "Select a JSON file to flatten" is not appropriate in this context.

There could also be a success message to inform the user the file has been pre-processed successfully.

cc @sabahfromlondon

**Comment by sabahfromlondon** [comment]
@sorenabell I'll update you with a suggested user journey in the morning.

**Comment by sabahfromlondon** [comment]
@sorenabell the wireframe for a user arriving from the registry was slightly different to those uploading data. See attached screenshot.

Was a different screen created for that purpose? I'd like to be able to see it if I can.

I think I want to adapt the content from the design below in any case, so it might be easier if I can markup.

![01_home_from_registry__lite___manual_](https://user-images.githubusercontent.com/11212467/119645587-17a24300-be16-11eb-8f39-a108cf56774a.png)

**Comment by sorenabell** [comment]
@sabahfromlondon @jpmckinney Where/how could we receive the information for those 3 new fields?

**Comment by sorenabell** [comment]
@sabahfromlondon We added all three fields for the display. If any of them are empty, they just won't be displayed.
Please try out this example:
https://ocp12.open-contracting.org/#/upload-file?lang=en_US&url=f6fb1d89-32f4-40af-a334-3437dde16d05

![image](https://user-images.githubusercontent.com/5451803/121529535-29363e00-ca05-11eb-95fc-d2c61294cc01.png)

**Comment by sabahfromlondon** [comment]
@sorenabell looks good. A few things:

1. When I land on the page, there is a notification that pops up on the top right. This should be for uploaded data only and not if a user arrives from the data registry.
2. The FAQs are not relevant for users that have arrived from the Data Registry, so I would remove and just keep for users that have uploaded data.

On the content, I just want to clean up the text a bit. Please use the following text for the two paragraphs in the screen:

"The Flatten Tool converts JSON OCDS data to Excel or CSV and helps you to understand what data is contained in the file.

Datasets can be very large and so it is recommended that you only select and flatten data that you actually want to use."

**Comment by sorenabell** [comment]
1. Shouldn't there still be a notification about successful input of the file from one tool into another?
2. +
3. This text should be changed just for users who came from Data Registry?

**Comment by sabahfromlondon** [comment]
1. I don't think the notification makes sense in this content. Users are getting their data from the OCP Data Registry so its odd that another OCP tool needs is checking the data again

3. Yes just for the users that came from the Data Registry. The content for users that are uploading data can stay as it is

**Comment by sorenabell** [comment]
Great, understood.
One more thing, if we are talking about FAQs - should we remove only the blocks labeled FAQ or the block on the first step ("If you would like to convert CSV data to JSON, please use the older Command-Line tool...") is to be removed too?

**Comment by sabahfromlondon** [comment]
I don't think either of those FAQs are relevant to users that arrive from the Data Registry so we can remove the whole thing

**Comment by sorenabell** [comment]
Please check the updates (e.g. https://ocp12.open-contracting.org/#/upload-file?lang=en_US&url=f6fb1d89-32f4-40af-a334-3437dde16d05)

![image](https://user-images.githubusercontent.com/5451803/123136369-872e4100-d45b-11eb-9337-e40ac1fe69c3.png)

**Comment by sabahfromlondon** [comment]
Looks good, thank you :)
