### ISSUE TITLE
Change step names

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/spoonbill-web#232]
We've looked again at the names for the different steps and think some of the names for these could be better and will help to manage expectations for what is actually possible for a user to do.

<img width="399" alt="Screenshot 2021-05-26 114538" src="https://user-images.githubusercontent.com/11212467/119647364-1540e880-be18-11eb-9629-a1b3e6565410.png">

Can we change "Customize tables" to "Preview tables" ?
Can we change "Edit tables" to "Edit headings" ?

**Comment by sorenabell** [comment]
![image](https://user-images.githubusercontent.com/5451803/119963819-32f58580-bfb1-11eb-9c76-a1e397f715fe.png)
