### ISSUE TITLE
Integration with data registry (add Country and Date range)

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/spoonbill-web#239]
When the user arrives at the flatten tool via the data registry i.e. not via the file upload route, the data registry needs to pass through information to the flatten tool about:

- the country name for the dataset e.g. United Kingdom Contracts Finder
- the data date range (MM-YYYY)

for the flatten tool to convert the data from JSON to tabular data

**Comment by jpmckinney** [comment]
@sorenabell The call notes mention "Need to know where fields are received". Can the fields above be passed as additional parameters in the existing API call?

**Comment by sorenabell** [comment]
Yes, but this will require some minor updates on our side.

**Comment by sorenabell** [comment]
@sabahfromlondon I checked the flow with the following link https://flatten.open-contracting.org//#/upload-file?lang=en_US%7Ces&url=259078f6-c06b-4a2e-8966-e19189e1fb86, it still works correctly. But it is just an example. Maybe someone from Datlab could share the links they are currently using, so we could understand the differences.

**Comment by sabahfromlondon** [comment]
@sorenabell I remember us discussing this screen a while ago with you and @olehchepak where I mentioned that when the user arrives from the data registry the upload data screen is not the right one (I can't find the issue now). The original wireframe looks like this:

![01_home_from_registry__lite___manual_](https://user-images.githubusercontent.com/11212467/130482647-4a4b3af8-7243-42e7-8847-a5d8f84b9a82.png)

Are you sure there is not another screen?

**Comment by sorenabell** [comment]
It was issue #229. 
@sabahfromlondon Let us know what we should do with the titles of the steps since currently we have 5 of them and Select data includes other content, different from this wireframe.

**Comment by sorenabell** [comment]
The same design contains "Back to data details" link, but we don't have any Data Registry link at the moment that we could refer users to.

**Comment by sabahfromlondon** [comment]
@sorenabell thanks for sharing the screen, looks really nice. I need to discuss a couple of things with James first in our meeting this afternoon, so will come back to you after that

**Comment by sorenabell** [comment]
This helps immensely, thank you.

**Comment by sorenabell** [comment]
@sabahfromlondon Please test the updated flow: https://www.loom.com/share/95eae847300746149b98009d81436be2.

You can do that by inserting `file:///data/storage/exporter_dumps/australia/54/2009.jsonl.gz` into the Upload URL field. (The `test` text in Spanish needs to be translated https://www.transifex.com/open-contracting-partnership-1/spoonbill/translate/#es/web-app-ui/330722124?q=text%3A'Data+you+selected+needs+to+be+converted+into+an', I added test to test whether translation is working properly.)

Currently, it is just a minor fix to show you the UI, the way to determine whether user came from Data registry is discussed here #347

**Comment by sabahfromlondon** [comment]
@sorenabell are you sure the video is the correct one?

**Comment by sorenabell** [comment]
Yes. As you can see in the video, we have just 4 steps.
You can test the flow that user will see moving from Data Registry to spoonbill by inserting `file:///data/storage/exporter_dumps/australia/54/2009.jsonl.gz` into the Upload URL field on production.

**Comment by sabahfromlondon** [comment]
Ok I can see the 4 steps, but why is the journey from the upload step?

**Comment by sorenabell** [comment]
It is just roundabout to test the UI before #347 (the way to determine where the user came from) is ready.

**Comment by sabahfromlondon** [comment]
Ok I see. Was very confusing at first, but the 4 steps looks good.

**Comment by jpmckinney** [comment]
Seems like this is done, so closing.
