### ISSUE TITLE
Order of tables in preview

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/spoonbill-web#253]
@sorenabell I'm sure I mentioned it in a previous issue that the order of the tables in the Preview Tables section is important. The reason being we want the tables to follow the contracting process, so :Parties, Planning, Tender, Award, Contract, Documents, Milestones, Amendments. 

I can still see that the order of the tables appears to depend on the select tables step. 

<img width="863" alt="Screenshot 2021-06-03 144335" src="https://user-images.githubusercontent.com/11212467/120672627-63925f00-c48a-11eb-9fd8-23182426fa7e.png">

**Comment by sorenabell** [comment]
The order was fixed, please check.

![image](https://user-images.githubusercontent.com/5451803/125745312-6d0c65fd-e40f-4208-a4f4-33a6ce6b8eed.png)

**Comment by sabahfromlondon** [comment]
The order looks correct for the examples I have tried but I've now started seeing that some of the tables are not appearing. This was not happening before...

The screenshot shows that I have selected all the tables
<img width="712" alt="Screenshot 2021-07-15 092458" src="https://user-images.githubusercontent.com/11212467/125755427-0ec58095-986b-407d-9dcc-dcf890ab5319.png">


However when I proceed to the next step, the Planning and Tenders tables are missing:
<img width="866" alt="Screenshot 2021-07-15 092837" src="https://user-images.githubusercontent.com/11212467/125755596-e6ecbda0-e01e-44a8-b82d-4c16ddb67d7b.png">

**Comment by sorenabell** [comment]
Please check once more, maybe not all the latest changes were applied.

**Comment by sabahfromlondon** [comment]
@sorenabell I've tested with three different files. All working properly! Thank you :)
