### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/spoonbill-web#262]
For some reason the merge request 0de2664c2634d4c02d094168f3f7b7eb4b10e7c1 caused CI to fail, even though the commit(s) it contains didn't fail.

**Comment by sorenabell** [comment]
@jpmckinney There are some issues on preview step #205 that cause robot tests to fail.
While we are working on that issue, we made this particular robot test non-critical so further merges will not fail.
