### ISSUE TITLE
"test data" label in the website

### ISSUE THREAD

**Issue by yolile** [open-contracting/spoonbill-web#269]
![image](https://user-images.githubusercontent.com/6834122/122097902-3163f400-cdde-11eb-902b-14aba52a5af4.png)
should that be there?

**Comment by sabahfromlondon** [comment]
@yolile I saw this before and thought I had created a ticket, but can't find it! The text you highlighted should not be there

**Comment by sorenabell** [comment]
I think it was just a test element and it was removed in later commits. Please check.

**Comment by yolile** [comment]
Yes, it is removed now, thanks!
