### ISSUE TITLE
Remove cases of "Page Unresponsive" popup

### ISSUE THREAD

**Issue by sorenabell** [open-contracting/spoonbill-web#303]
Splitting out the arrays is a bit slow and my browser (Chrome) was coming up with a "Page Unresponsive" popup. If I select wait, then the tool does come good a short time later and successfully splits out the data. I tested this multiple times.

![image](https://user-images.githubusercontent.com/5451803/126306681-1fe4a5c7-206f-4503-8680-5ff1a197ffa3.png)

**Comment by sabahfromlondon** [comment]
To add more context, the issue only occurred when I was flattening very large file.

**Comment by sorenabell** [comment]
@sabahfromlondon could you share this large file with us so we could test the loading time with it?

**Comment by sabahfromlondon** [comment]
@sorenabell I think I used this one when testing:

[1993.jsonl.gz](https://github.com/open-contracting/spoonbill-web/files/6856676/1993.jsonl.gz)

**Comment by sorenabell** [comment]
Thanks

**Comment by sorenabell** [comment]
The issue was fixed with new splitting behavior #306
