### ISSUE TITLE
Add limit to the number of rows displayed in preview

### ISSUE THREAD

**Issue by sorenabell** [open-contracting/spoonbill-web#304]
The split out arrays contain all of the rows in the dataset and not just the first five rows. Not terrible, especially as you have the ability to scroll for the table

**Comment by sorenabell** [comment]
@sabahfromlondon let's specify one more time, the number of rows displayed in the preview table should be 5 (plus heading)?
Should this limit be set for both the main table and the split ones?

**Comment by sorenabell** [comment]
@sabahfromlondon we will add this task to the pipeline as soon as you confirm the requirements.

**Comment by sabahfromlondon** [comment]
Yes five rows, plus the heading, for both the main table and the split tables. Thanks :)

**Comment by sorenabell** [comment]
Fixed. Please review.
