### ISSUE TITLE
Preview step: vertical scroll dissapears after table is restored

### ISSUE THREAD

**Issue by sorenabell** [open-contracting/spoonbill-web#305]
If you remove a table and then restore it then not only do you get the whole table, but the scroll for the table is lost. Again not terrible, but say you have two split out tables and you remove and restore the first table. You may have to scroll a long way down to view the second table.

**Comment by sorenabell** [comment]
@sabahfromlondon this is fixed

**Comment by sabahfromlondon** [comment]
Tested again. Looks good to me. Thank you
