### ISSUE TITLE
Rename FileNotFoundError notification

### ISSUE THREAD

**Issue by sorenabell** [open-contracting/spoonbill-web#307]
We have exception `FileNotFoundError: [Errno 2] No such file or directory: '/data/django/f90d1d20-7903-431c-b53c-f5c78a54e9fc/b1b...` when someone uses a link to the already deleted file.
We can create a nice notification for this case. Something like `This file is old and was already deleted. Please upload a new one.`

@sabahfromlondon what do you think?

**Comment by sabahfromlondon** [comment]
@sorenabell yes I agree. A friendlier message is needed. Please use the following wording:

"This linked file is no longer available. Please supply a new URL"

**Comment by sabahfromlondon** [comment]
@sorenabell do you have a file that I can use to test the error message? Thanks

**Comment by sorenabell** [comment]
I tried with this link https://ocp12.open-contracting.org/#/select-data?lang=en_US&upload=f90d1d20-7903-431c-b53c-f5c78a54e9fc%2Fb1bb70dc8861423ebb4d6c29e61658c2.json

**Comment by sabahfromlondon** [comment]
Hmm I didn't get an error message using this file. After one minute it was still saying "upload in progress", see screenshot

<img width="556" alt="Screenshot 2021-07-29 132340" src="https://user-images.githubusercontent.com/11212467/127491148-fff66527-5f6d-43e0-8421-f70d1f230bba.png">

**Comment by sorenabell** [comment]
Just following this link doesn't open you this screen?
![image](https://user-images.githubusercontent.com/5451803/127491281-00e54967-c6a9-4b62-aade-b27d2ccf87d1.png)

**Comment by sabahfromlondon** [comment]
Sorry I'm not paying attention. I do see that screen when I click the link.

**Comment by sabahfromlondon** [comment]
I wanted to be able to test that I can:

1. Successfully upload via a URL
2. Remove the URL 
3. Check to see if the notification comes up

Is this possible?

**Comment by sorenabell** [comment]
URL (and file) is automatically removed after 5 days, I don't think that we have another way to remove it quicker.
