### ISSUE TITLE
Authorization for POST /api/urls/

### ISSUE THREAD

**Issue by sorenabell** [open-contracting/spoonbill-web#347]
@jpmckinney We have two issues associated with Data Registry integration:
1. @sabahfromlondon asked to differentiate flows that start from the Data Registry and from the spoonbill app itself (#239).
2. There is a security risk when an anonymous user can use local file's paths in `POST /api/urls/`.

To solve both issues, we can introduce optional authentication for `POST /api/urls/` endpoint. 
It would:
1. allow Data Registry to be authorized. This would let us differentiate between the jobs of users and jobs from the Data Registry.
2. allow local paths only for authorized requests.

Additional risk: Datlab would need to add Authentication header to their POST request with valid credentials.

**Comment by sorenabell** [comment]
It seems that this is a fragile way to limit access. It would be inside the Docker network, so we don't really know what would be the Data Registry's IP. Moreover, it may change after the server is re-launched.

**Comment by jpmckinney** [comment]
Basic Authentication sounds fine, and it will be easy to change the data registry to support it.

**Comment by sorenabell** [comment]
We added Authorization for the app. Instructions are here https://github.com/open-contracting/spoonbill-web/blob/main/core/views.py#L222. Please check.
Currently, it is present on the staging website.

**Comment by sorenabell** [comment]
We added Authorization for the app. Instructions are here https://github.com/open-contracting/spoonbill-web/blob/main/core/views.py#L222. Please check.
Currently, it is present on the staging website

**Comment by sorenabell** [comment]
@jpmckinney Currently the production was updated with this feature. Instructions for authorization are here https://flatten.open-contracting.org/api/urls/.
Please let me know if you need help with token or communication with Datlab on this task.

**Comment by jpmckinney** [comment]
Great. I've currently stopped all registry containers while I do some reconfiguration. I'll add support for Authorization before bringing them back up.

**Comment by sorenabell** [comment]
@jpmckinney Please note that for front-end to display the proper UI, the `author` has to be `Dataregistry`.

**Comment by sorenabell** [comment]
@jpmckinney Yes, I've shared password for `Dataregistry` (capital D) in Slack.

**Comment by jpmckinney** [comment]
@yolile Please prepare a PR for the data registry to add settings for `SPOONBILL_API_USERNAME` and `SPOONBILL_API_PASSWORD` and use them here:

https://github.com/open-contracting/data-registry/blob/c5a90b015223b0a7597fe6800ab68a7d988b8905/data_registry/views/general.py#L195

Normally, I would just add the user/pass to the existing `FLATTEN_URL` setting, but that URL is also used for a public redirect.

I've sent the credentials in Slack.

**Comment by yolile** [comment]
The integration was done in https://github.com/open-contracting/data-registry/issues/162 and the authentication is working well.
