### ISSUE TITLE
Remove ARG and ENV from frontend/Dockerfile

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/spoonbill-web#429]
As with other repositories, these should be set via docker-compose and .env, not via Dockerfile.

`VUE_APP_WEBSOCKET_URL|VUE_APP_API_URL|VUE_APP_SENTRY_DSN`

**Comment by yolile** [comment]
I guess they are used that way because they are used later for `npm run build`

https://github.com/open-contracting/spoonbill-web/blob/3385b117ce3cfa1551537d2fc75a06b2c4a23667/frontend/Dockerfile#L17-L20

**Comment by jpmckinney** [comment]
Yes, I mean they shouldn't be there either, I think.

**Comment by jpmckinney** [comment]
Done in 36fb9605112905dd537537748fa384c7d00cdac8
